# Generated by Django 4.0.6 on 2025-02-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_estimada', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
                ('presupuesto', models.CharField(max_length=100)),
                ('foto', models.FileField(upload_to='edificaciones/')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('id_edificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to='Comerciales.edificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recurso', models.CharField(choices=[('humano', 'Humano'), ('material', 'Material'), ('financiero', 'Financiero')], max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.CharField(max_length=50)),
                ('costo', models.CharField(max_length=50)),
                ('fecha_asignacion', models.DateTimeField()),
                ('id_edificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='Comerciales.edificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('foto', models.FileField(upload_to='propietarios/')),
                ('direccion', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=255)),
                ('id_edificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios', to='Comerciales.edificacion')),
            ],
        ),
        migrations.CreateModel(
            name='FechaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField()),
                ('estado_entrega', models.CharField(max_length=50)),
                ('id_edificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_entrega', to='Comerciales.edificacion')),
            ],
        ),
    ]
