# Generated by Django 4.0.6 on 2025-02-08 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comerciales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechaentrega',
            name='id_edificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_entrega', to='Comerciales.tienda'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='id_edificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios', to='Comerciales.tienda'),
        ),
    ]
