# Generated by Django 4.0.6 on 2025-02-08 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comerciales', '0003_alter_fechaentrega_id_edificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechaentrega',
            name='id_edificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_entrega', to='Comerciales.tienda'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='id_edificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios', to='Comerciales.tienda'),
        ),
    ]
