# Generated by Django 4.0.6 on 2025-02-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comerciales', '0004_alter_fechaentrega_id_edificacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fechaentrega',
            old_name='id_edificacion',
            new_name='tienda',
        ),
        migrations.RenameField(
            model_name='propietario',
            old_name='id_edificacion',
            new_name='tienda',
        ),
    ]
